// ignore_for_file: non_constant_identifier_names
class APIPostListing {
  String kind;
  APIPostListingData data;
  static APIPostListing fromJson(data) {
    final postListing = APIPostListing();
    postListing.kind = data["kind"];
    postListing.data = APIPostListingData.fromJson(data["data"]);
    return postListing;
  }
}

class APIPostListingData {
  String modhash;
  int dist;
  String before;
  String after;
  List<APIPost> children;
  static APIPostListingData fromJson(data) {
    final postListingData = APIPostListingData();
    postListingData.modhash = data["modhash"];
    postListingData.dist = data["dist"];
    postListingData.before = data["before"];
    postListingData.after = data["after"];
    postListingData.children = [];
    for (var post in data["children"]) {
      postListingData.children.add(APIPost.fromJson(post));
    }
    return postListingData;
  }
}

class APIPost {
  APIPostData data;
  String kind;
  static APIPost fromJson(data) {
    final post = APIPost();
    post.kind = data["kind"];
    post.data = APIPostData.fromJson(data["data"]);
    return post;
  }
}

class APIPostData {
  dynamic approved_at_utc;
  String subreddit;
  String selftext;
  List user_reports;
  bool saved;
  dynamic mod_reason_title;
  int gilded;
  String title;
  String subreddit_name_prefixed;
  bool hidden;
  int pwls;
  String link_flair_css_class;
  int downs;
  dynamic top_awarded_type;
  String parent_whitelist_status;
  bool hide_score;
  String name;
  bool quarantine;
  String link_flair_text_color;
  double upvote_ratio;
  dynamic author_flair_background_color;
  String subreddit_type;
  int ups;
  int total_awards_received;
  dynamic media_embed;
  dynamic author_flair_template_id;
  bool is_original_content;
  String author_fullname;
  dynamic secure_media;
  bool is_reddit_media_domain;
  bool is_meta;
  dynamic category;
  dynamic secure_media_embed;
  String link_flair_text;
  bool can_mod_post;
  int score;
  dynamic approved_by;
  bool author_premium;
  String thumbnail;
  dynamic edited;
  dynamic author_flair_css_class;
  dynamic author_flair_richtext;
  dynamic gildings;
  dynamic content_categories;
  bool is_self;
  dynamic mod_note;
  double created;
  String link_flair_type;
  int wls;
  dynamic removed_by_category;
  dynamic banned_by;
  String author_flair_type;
  String domain;
  bool allow_live_comments;
  dynamic selftext_html;
  dynamic likes;
  String suggested_sort;
  dynamic banned_at_utc;
  String url_overridden_by_dest;
  dynamic view_count;
  bool archived;
  bool no_follow;
  bool is_crosspostable;
  bool pinned;
  bool over_18;
  List all_awardings;
  List awarders;
  bool media_only;
  String link_flair_template_id;
  bool can_gild;
  bool spoiler;
  bool locked;
  dynamic author_flair_text;
  List treatment_tags;
  bool visited;
  dynamic removed_by;
  dynamic num_reports;
  dynamic distinguished;
  String subreddit_id;
  dynamic mod_reason_by;
  dynamic removal_reason;
  String link_flair_background_color;
  String id;
  bool is_robot_indexable;
  int num_duplicates;
  dynamic report_reasons;
  String author;
  dynamic discussion_type;
  int num_comments;
  bool send_replies;
  dynamic media;
  bool contest_mode;
  bool author_patreon_flair;
  dynamic author_flair_text_color;
  String permalink;
  String whitelist_status;
  bool stickied;
  String url;
  int subreddit_subscribers;
  double created_utc;
  int num_crossposts;
  List mod_reports;
  bool is_video;
  String post_hint;
  static APIPostData fromJson(data) {
    final postData = APIPostData();
    postData.approved_at_utc = data["approved_at_utc"];
    postData.subreddit = data["subreddit"];
    postData.selftext = data["selftext"];
    postData.user_reports = data["user_reports"];
    postData.saved = data["saved"];
    postData.mod_reason_title = data["mod_reason_title"];
    postData.gilded = data["gilded"];
    postData.title = data["title"];
    postData.subreddit_name_prefixed = data["subreddit_name_prefixed"];
    postData.hidden = data["hidden"];
    postData.pwls = data["pwls"];
    postData.link_flair_css_class = data["link_flair_css_class"];
    postData.downs = data["downs"];
    postData.top_awarded_type = data["top_awarded_type"];
    postData.parent_whitelist_status = data["parent_whitelist_status"];
    postData.hide_score = data["hide_score"];
    postData.name = data["name"];
    postData.quarantine = data["quarantine"];
    postData.link_flair_text_color = data["link_flair_text_color"];
    postData.upvote_ratio = data["upvote_ratio"];
    postData.author_flair_background_color =
        data["author_flair_background_color"];
    postData.subreddit_type = data["subreddit_type"];
    postData.ups = data["ups"];
    postData.total_awards_received = data["total_awards_received"];
    postData.media_embed = data["media_embed"];
    postData.author_flair_template_id = data["author_flair_template_id"];
    postData.is_original_content = data["is_original_content"];
    postData.author_fullname = data["author_fullname"];
    postData.secure_media = data["secure_media"];
    postData.is_reddit_media_domain = data["is_reddit_media_domain"];
    postData.is_meta = data["is_meta"];
    postData.category = data["category"];
    postData.secure_media_embed = data["secure_media_embed"];
    postData.link_flair_text = data["link_flair_text"];
    postData.can_mod_post = data["can_mod_post"];
    postData.score = data["score"];
    postData.approved_by = data["approved_by"];
    postData.author_premium = data["author_premium"];
    postData.thumbnail = data["thumbnail"];
    postData.edited = data["edited"];
    postData.author_flair_css_class = data["author_flair_css_class"];
    postData.author_flair_richtext = data["author_flair_richtext"];
    postData.gildings = data["gildings"];
    postData.content_categories = data["content_categories"];
    postData.is_self = data["is_self"];
    postData.mod_note = data["mod_note"];
    postData.created = data["created"];
    postData.link_flair_type = data["link_flair_type"];
    postData.wls = data["wls"];
    postData.removed_by_category = data["removed_by_category"];
    postData.banned_by = data["banned_by"];
    postData.author_flair_type = data["author_flair_type"];
    postData.domain = data["domain"];
    postData.allow_live_comments = data["allow_live_comments"];
    postData.selftext_html = data["selftext_html"];
    postData.likes = data["likes"];
    postData.suggested_sort = data["suggested_sort"];
    postData.banned_at_utc = data["banned_at_utc"];
    postData.url_overridden_by_dest = data["url_overridden_by_dest"];
    postData.view_count = data["view_count"];
    postData.archived = data["archived"];
    postData.no_follow = data["no_follow"];
    postData.is_crosspostable = data["is_crosspostable"];
    postData.pinned = data["pinned"];
    postData.over_18 = data["over_18"];
    postData.all_awardings = data["all_awardings"];
    postData.awarders = data["awarders"];
    postData.media_only = data["media_only"];
    postData.link_flair_template_id = data["link_flair_template_id"];
    postData.can_gild = data["can_gild"];
    postData.spoiler = data["spoiler"];
    postData.locked = data["locked"];
    postData.author_flair_text = data["author_flair_text"];
    postData.treatment_tags = data["treatment_tags"];
    postData.visited = data["visited"];
    postData.removed_by = data["removed_by"];
    postData.num_reports = data["num_reports"];
    postData.distinguished = data["distinguished"];
    postData.subreddit_id = data["subreddit_id"];
    postData.mod_reason_by = data["mod_reason_by"];
    postData.removal_reason = data["removal_reason"];
    postData.link_flair_background_color = data["link_flair_background_color"];
    postData.id = data["id"];
    postData.is_robot_indexable = data["is_robot_indexable"];
    postData.num_duplicates = data["num_duplicates"];
    postData.report_reasons = data["report_reasons"];
    postData.author = data["author"];
    postData.discussion_type = data["discussion_type"];
    postData.num_comments = data["num_comments"];
    postData.send_replies = data["send_replies"];
    postData.media = data["media"];
    postData.contest_mode = data["contest_mode"];
    postData.author_patreon_flair = data["author_patreon_flair"];
    postData.author_flair_text_color = data["author_flair_text_color"];
    postData.permalink = data["permalink"];
    postData.whitelist_status = data["whitelist_status"];
    postData.stickied = data["stickied"];
    postData.url = data["url"];
    postData.subreddit_subscribers = data["subreddit_subscribers"];
    postData.created_utc = data["created_utc"];
    postData.num_crossposts = data["num_crossposts"];
    postData.mod_reports = data["mod_reports"];
    postData.is_video = data["is_video"];
    postData.post_hint = data["post_hint"];
    return postData;
  }
}
