name: Build
on: push
jobs:
  lint:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: "12.x"
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: "1.22.4"
      - run: flutter pub get
      - run: dart analyze
  build:
    requires: lint
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: "12.x"
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: "1.22.4"
      - run: flutter pub get
      - run: flutter build apk
      - run: flutter build ios --release --no-codesign
  test:
    requires: build
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: "12.x"
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: "1.22.4"
      - run: flutter pub get
      - run: |
          flutter drive \
            --driver=test_driver/integration_test.dart \
            --target=integration_test/all_test.dart
